### ISSUE TITLE
女性声纹识别区别度低

### ISSUE THREAD

**Issue by west3316** [liuxp0827/govpr#1]
你好，我使用了govpr做声纹识别实验时发现女性声纹识别得分上区别不明显，身份鉴定不准确，请问能够通过什么手段改善。

（识别实验采用了项目里自带的ubm文件，实验程序实现完全参照example中的程序开发）

我现在完全没有解决的思路，还请提示，谢谢！

**Comment by liuxp0827** [comment]
首先,语音格式为wav格式(采样率16000,16bits,单声道).
其次,男女声纹识别得分上确实差异比较大,这套代码都是一些简易的实现.理论上应该先对性别进行检测,对不同性别采用不同的阈值来区分,如果时间允许会加上这个功能..
最后,方便的话,可以给我发六段测试语音到我的邮箱liuxp_0325@qq.com,我找时间看看.

**Comment by west3316** [comment]
我目前还没有能力完善它，不过还是谢谢你的提示。

**Comment by liuxp0827** [comment]
语音识别，声纹识别是我读硕士的时期的研究方向，已经很长时间没碰了，算法层面的东西没办法给你提供什么帮助。这个项目只是闲时用golang造了一遍轮子，还有java版的搞了一半没空做了先停下来了。如果你是搞说话人识别研究的，这套代码也就适合入个门，如果是想要出产品的话，还是有一定差距的。

**Comment by liuxp0827** [comment]
你好,你的测试语音我已经测试过了.
语音没有问题,默认测试程序是开启删除语音中的静音(无效语音)部分的,可能由于你的测试语音是一整段20个数字的,所以静音裁剪就不够准确,导致得分偏低.
给你的建议如下:
1. 将example/main.go下的NewEngine函数下的NewVPREngine第三个参数设为false,实测最终得分为1.174976.
![22](https://cloud.githubusercontent.com/assets/4446722/21085894/29440362-c052-11e6-8bd1-9f24763d6205.jpg)

2. 建议训练语音以8个数字为一段语音,录取的语音时最好四个数字小停顿下,例如 '1234 5678'
3. 增加训练语音数据,一般测试数据以2中所说的8个数字语音为例,建议在5条语音数据以上,最好不要像你的训练数据那样,一大串语音.

**Comment by liuxp0827** [comment]
另外,数字中最好不要有 "1" 这个数字,ubm的训练数据是不包含 "1" ,因为1有"yi"和"yao"两个读音.所以训练数据和验证数据都不要包含"1"这个数据,也不要有连续相同的数字出现.
