### ISSUE TITLE
example错误

### ISSUE THREAD

**Issue by 12wang3** [liuxp0827/govpr#2]
运行example时，报错
2017/03/04 21:29:18 [engine.go:59] [E] gzip: invalid header 
2017/03/04 21:29:18 [main.go:73] [F] model load failed: gzip: invalid header 
但将file/vprfile.go 中的NewVPRFile函数不使用gzip，而是直接换成注释里的内容，问题解决。

**Comment by liuxp0827** [comment]
谢谢指出错误，之前想要加gzip的压缩，后来发现没必要，代码忘了改回来就给提交了~
